import Head from 'next/head'
import Image from 'next/image'

export  function Ratingsection({sheetdata} : any) {
// Sort results by id in descending order, take two
// and return the age as an integer.

fetch('https://sheetdb.io/api/v1/105rynq2fk86g')
  .then((response) => response.json())
  .then((data) => console.log(data));

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1>
          <h1>hello world</h1>
          {sheetdata}
        </h1>
      </main>
    </div>
  )
}

export default Ratingsection

export async function getServerSideProps() {
  const req = await fetch('http://localhost:3000/utils/ratesheet');
  const res = await req.json();

  return {
    props: {
      sheetdata: res.data
    }
  }
}