"use client"
import Head from 'next/head'
import Image from 'next/image'
import Axiosrequest from '@/utils/Axiosrequest';
import { useEffect } from 'react';
export  function Ratingsection({sheetdata} : any) {
// Sort results by id in descending order, take two
// and return the age as an integer.

const HandlefetchRate = async ()=>{
  try {
    
    const res = await  Axiosrequest.get(`${process.env.NEXT_PUBLIC_RATESHEET}`)
    if(res.status === 200){
    console.log(res.data)

    }
    console.log(res.status)
  } catch (error) {
    
  }



}
useEffect(()=>{
  HandlefetchRate()
})

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
          <h1>hello world</h1>
        <h1>
          {sheetdata}
        </h1>
      </main>
    </div>
  )
}

export default Ratingsection
