"use client";
import Head from "next/head";
import Image from "next/image";
import Axiosrequest from "@/utils/Axiosrequest";
import React, { useRef, useState, useEffect } from "react";
import { Virtual, Navigation, Pagination } from "swiper/modules";
import SwiperCore from "swiper/core";

import { Swiper, SwiperSlide } from "swiper/react";
// import 'swiper/swiper-bundle.css';

// // Install Swiper modules\

export function Ratingsection({ sheetdata }: any) {
  const [swiperRef, setSwiperRef] = useState<SwiperCore>();
  const appendNumber = useRef(500);
  const prependNumber = useRef(1);
  // Create array with 500 slides

  const [slides, setSlides] = useState(
    Array.from({ length: 500 }).map((_, index) => `Slide ${index + 1}`)
  );

  const prepend = () => {
    setSlides([
      `Slide ${prependNumber.current - 2}`,
      `Slide ${prependNumber.current - 1}`,
      ...slides,
    ]);
    prependNumber.current = prependNumber.current - 2;
    if (swiperRef) {
      swiperRef.slideTo(swiperRef.activeIndex + 2, 0);
    }
  };

  const append = () => {
    setSlides([...slides, "Slide " + ++appendNumber.current]);
  };

  const slideTo = (index: number) => {
    if (swiperRef) {
      swiperRef.slideTo(index, 0);
      swiperRef.slideTo(index - 1, 0);
    }
  };

  const HandlefetchRate = async () => {
    try {
      const res = await Axiosrequest.get(
        `${process.env.NEXT_PUBLIC_RATESHEET}`
      );
      if (res.status === 200) {
        console.log(res.data);
      }
      console.log(res.status);
    } catch (error) {}
  };
  useEffect(() => {
    HandlefetchRate();
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>hello world</h1>
        <h1>{sheetdata}</h1>
      </main>
    </div>
  );
}

export default Ratingsection;
